### ISSUE TITLE
Promote UDFs to elements plan

### ISSUE THREAD

**Issue by nllong** [BuildingSync/schema#150]
Determine which UDFs in this file (and possible others) should be promoted to UDFs. This issue is a meta-issue and should result in multiple other issues and or pull requests.

https://github.com/BuildingSync/schema/blob/develop/examples/AT_example_NYC_audit_report_property.xml

**Comment by corymosiman12** [comment]
First task was prioritizing. We currently have the following categories for priority 1 UDFs:


Category | Count
-- | --
Building | 3
Measure | 1
Report | 9
Section | 3
System | 14
Grand Total | 30

Progress being tracked here: https://docs.google.com/spreadsheets/d/1LaztYTrT7_iPQTcTDEQZAB2fVJ23G3Wo/edit#gid=595543811

Proposals / implementations will be added for each individual item shortly.
