### ISSUE TITLE
Change ID attributes for following elements to use="required"

### ISSUE THREAD

**Issue by corymosiman12** [BuildingSync/schema#187]
Premises:
- Facility
- Site
- Building
- Section

Systems:
- HVACSystem
- HeatingPlant
- CoolingPlant
- CondensorPlant
- HeatingSource
- CoolingSource
- Delivery
- OtherHVACSystem
- LightingSystem
- DomesticHotWaterSystem
- PumpSystem
- FanSystem
- MotorSystem
- WallSystem
- RoofSystem
- FenestrationSystem
- ExteriorFloorSystem
- FoundationSystem
- CriticalITSystem
- PlugLoad
- ProcessLoad
- ConveyanceSystem
- OnsiteStorageTransmissionGenerationSystem
- AirInfiltrationSystem

Schedules & Measures:
- Schedule
- Measure

Reports:
- Report
- Scenario
- ResourceUse
- Qualification
- Utility

Contacts:
- Contact

Tenants:
- Tenant

**Comment by corymosiman12** [comment]
@markborkum @nllong thoughts?  Other types to add?

**Comment by markborkum** [comment]
@corymosiman12 Personally, I'd add every single element with an "ID" attribute to the list. In Audit Template, if an element has an "ID" attribute, then we set it to a locally-unique value (within the scope of the enclosing document).
