### ISSUE TITLE
Review use of talking about standards within documentation

### ISSUE THREAD

**Issue by corymosiman12** [BuildingSync/schema#197]
Make sure everything is consistent.  Do we use:

- ASHRAE Standard 211-2018
- Standard 211-2018
- https://bedes.lbl.gov/related-efforts/spc-211-standard-commercial
- ... etc.

**Comment by corymosiman12** [comment]
Terms searched:
- 211
- ASHRAE
- Standard
- std
- 2018

References to other ASHRAE topics (i.e. 90.1, etc.) were not considered - this is only for references to the ASHRAE Standard 211 specifically.  There are only two instances where it is referred to in the docs:
https://github.com/BuildingSync/schema/blob/c729e7733b318ba9f49ecd68bb0974db1338a10a/BuildingSync.xsd#L975
https://github.com/BuildingSync/schema/blob/c729e7733b318ba9f49ecd68bb0974db1338a10a/BuildingSync.xsd#L5760

My preference would be to refer to it as `ASHRAE Standard 211-[year]`. Providing a year ensures that irrespective of new versions, the statement made holds firm.  Although I realize if we are following BEDES we should probably use `SPC 211 Standard for Commercial Building Energy Audits`.  

@nllong @markborkum opinions?

**Comment by markborkum** [comment]
@corymosiman12 Since it exists, I'd prefer to use BEDES term.

**Comment by corymosiman12** [comment]
Addressed in PR #201
