### ISSUE TITLE
Question concerning some "Other delivered" auc:FuelTypes

### ISSUE THREAD

**Issue by macintoshpie** [BuildingSync/schema#212]
I'd like to know what motivated the creation of `Other delivered-Exported` and `Other delivered-Onsite generated` enums for `auc:FuelType` because intuitively they seem a bit contradictory and I'm wondering if they could be removed.

I see these are options in Audit Template Tool as well:
<img width="378" alt="Screen Shot 2020-08-11 at 4 19 27 PM" src="https://user-images.githubusercontent.com/18518728/89954527-7f243480-dbee-11ea-9404-970efa7829ef.png">

**Comment by macintoshpie** [comment]
@markborkum do you have any insight on this?

**Comment by markborkum** [comment]
@macintoshpie As part of the harmonization of Audit Template and BuildingSync, the developers of both tools agreed to share all fuel types. To minimize disruption, it was also agreed to take the set union of the 2 preexisting sets of fuel types. The "other delivered" fuel types are of Audit Template.

In SPC 211 section 5.2.3.1:
> Building energy use includes imported energy such as electricity, natural gas, chilled water, steam, district hot water, propane, coal, compressed air, or any other source of supplied energy. These energy sources are included without regard for whether the energy is paid for by the building owner, tenant, operator, or other entity. 
 
In Audit Template, the term "metered" denotes energy that is paid for and the term "delivered" denotes energy that is not paid for (i.e., unmetered).

The building EUI calculations for the "Existing Building EUI/ECI" table in Audit Template account for all energy produced onsite and/or exported, including energy from "other delivered" sources (e.g., biomass).
