### ISSUE TITLE
Refactor auc:TimeSeries for more concise modeling

### ISSUE THREAD

**Issue by macintoshpie** [BuildingSync/schema#236]
As brought up in the 2020 proposal [_Add Associated Cost to TimeSeries_ Option 2](https://github.com/BuildingSync/schema/blob/develop/proposals/2020/Add%20Associated%20Cost%20to%20TimeSeries.md#option-2), we can more concisely model time series data by grouping reading types within a single `auc:TimeSeries` element.

This issue is a suggestion to revisit this design when creating version 3 of the schema.

For example (taken from the proposal)
```xml
<auc:Scenario>
    <auc:TimeSeriesData>
        <auc:TimeSeries>
            <!-- Add this element -->
            <auc:IntervalReading>
                <auc:Total>123</auc:Total>
                <auc:Peak>123</auc:Peak>
                <auc:Cost>1000</auc:Cost>
            </auc:IntervalReading>
            <auc:StartTimestamp>2019-01-01T00:00:00</auc:StartTimestamp>
            <auc:EndTimestamp>2019-02-01T00:00:00</auc:EndTimestamp>
            <auc:IntervalFrequency>Month</auc:IntervalFrequency>
            <auc:ResourceUseID IDref="ResourceUse-Electricity" />
        </auc:TimeSeries>
    </auc:TimeSeriesData>
</auc:Scenario>
```

**Comment by macintoshpie** [comment]
@nllong Is this something we still want to add to v3? Things to consider:
- AT import (is their support for v3 required?)
- SEED import (not too heavy of a lift for us)
- Existing schematron which reference meter readings (211, SEED, ...)
- How do other folks model TS data for multiple data types (reading, cost, etc) -- e.g. PM associates all readings to a single interval

**Comment by nllong** [comment]
We are going to table this until there is a more specific need.
