### ISSUE TITLE
Consider auc:MeasureName Refactor to minOccurs=1 maxOccurs=1

### ISSUE THREAD

**Issue by corymosiman12** [BuildingSync/schema#268]

**Comment by nllong** [comment]
This is a breaking change--correct?

**Comment by nllong** [comment]
Here is the proposal for when we implement. @macintoshpie is going to investigate proposal directory workflow.

# Limit MeasureName to one

## Overview

This proposal is limit the occurrence of MeasureName to 1 for all TechnologyCategories. This is a breaking change.

## Justification

Measures should represent singular energy conservation change ([BEDES](https://bedes.lbl.gov/bedes-online/reporting-level)). For a collection of changes one should use `PackageOfMeasures`.

## Implementation

Change `maxOccurs="1"` for every `auc:MeasureName`.
