### ISSUE TITLE
Fix typo in auc:eGRIDRegionCode enumeration

### ISSUE THREAD

**Issue by markborkum** [BuildingSync/schema#276]
"MORE" should be "MROE"

This issue also effects BEDES: https://bedes.lbl.gov/bedes-online/more

**Comment by nllong** [comment]
Nice find. I'll tag this for Version 3.0 fix since it will be a breaking change.

**Comment by nllong** [comment]
resolved by adding MROE. Will deprecate MORE in V3.0 per #283
