### ISSUE TITLE
Deprecate: MORE in auc:eGRIDRegionCode enumeration

### ISSUE THREAD

**Issue by nllong** [BuildingSync/schema#283]
**Describe the bug or data model issue**
MORE was a typo.

**Expected Behavior**
Should have been MROE. MROE was added to prevent a breaking change in this PR #279.

**Actual Behavior**
n/a

**Additional Context**
This was related to this issue #276

**Comment by JieXiong9119** [comment]
This typo was brought back while we refactor `eGRIDSubregionCode` in #387. We need to deprecate `MORE` again in version 3.0.

**Comment by nllong** [comment]
nice catch!
