### ISSUE TITLE
Refactor Measure to Track State of Implementation

### ISSUE THREAD

**Issue by corymosiman12** [BuildingSync/schema#284]
**Is your feature request related to a problem? Please describe.**

A `MeasureType` currently has multiple child elements relating to the state of implementation of a measure:
- `Recommended`
- `StartDate`
- `EndDate`
- `ImplementationStatus`
- `DiscardReason`

In the event where:
1. an audit is performed and different `ScenarioType/PackageOfMeasures` (POM) are analyzed and recommended
2. SOW is identified to undertake a particular POM implementation
2. the measures are implemented
3. M&V analysis is undertaken to determine whether the implemented measures had desired effects

Thoughts:
- This is a good use case for BSync and is an enabling workflow for many different potential applications
- We should have a clear definition for the document expectation at those different points in the auditing / M&V lifecycle

**Describe the solution you'd like**

Being able to track the state of a measure(s) implemented to the building as the BuildingSync document progresses through its lifespan is desirable.

**Describe alternatives you've considered**

**Additional context**

This likely needs to be undertaken in a holistic measure refactor effort.  Considerations:
- We should not need to create measure duplicates to identify state change
- Should data relating to the state of implementation for the measure be data of the Measure element itself OR tracked in the POM Scenario? (my vote would be to move that to the POM Scenario)
- Should a Measure be uniquely defined then by information NOT pertaining to the implementation of the measure?  Likely meaning that a Measure would just have the following info:
    - `TypeOfMeasure`
    - `SystemCategoryAffected`
    - `TechnologyCategories`
    - Maybe: `MeasureScaleOfApplication`
    - Then, the rest of the information would be defined per the POM Scenario (i.e. implementation costs, savings analysis, etc. etc.)

**Comment by macintoshpie** [comment]
@nllong is this something we could and want to include in v2.4.0 or v3.0.0?

**Comment by nllong** [comment]
I think this requirement was coming from a desire to more fully align with Std211. Unless we hear the need for this, I suggest we table it!

**Comment by macintoshpie** [comment]
I moved this request to Triage b/c I'm unaware of a specific request for this.

**Comment by macintoshpie** [comment]
Waiting until user requested
