### ISSUE TITLE
Release 2.3.0

### ISSUE THREAD

**Issue by nllong** [BuildingSync/schema#293]

**Comment by yan130** [comment]
Hi, I tested on Audit Template, it is working 3 days ago but get issue today:

`3:0: ERROR: Element '{http://buildingsync.net/schemas/bedes-auc/2019}BuildingSync', attribute 'version': [facet 'enumeration'] The value '2.3.0' is not an element of the set {'2.0.0-legacy', '0.2.0', '0.3.0', '1.0.0', '2.0.0-pr1', '2.0.0-pr2', '2.0.0', '2.1.0', '2.2.0-pr1', '2.2.0', '2.3.0-pr1'}.`

Could you help me with this?

**Comment by nllong** [comment]
Do you know if this is coming from schematron or just XML validation? The schema has been updated to support the enum, so I'm not sure where the error is originating: https://github.com/BuildingSync/schema/blob/develop/BuildingSync.xsd#L446

Let us know!
