### ISSUE TITLE
Search for simple types which need improved constraints

### ISSUE THREAD

**Issue by macintoshpie** [BuildingSync/schema#301]
There are probably multiple elements that are `xs:integer` when they should really be `xs:nonNegativeInteger` or `xs:positiveInteger`.
Another example, percentages are often decimal type, but we should constrain this.
Likely other types that should be updated as well

Task:
- scan the schema for types that need to be fixed and document them. E.g. search for generic xs types and determine if they should be further restricted
    - xs:string
    - xs:decimal
    - xs:integer
    - xs:boolean
    - xs:date
    - xs:time
- create tickets for fixing the types

**Comment by corymosiman12** [comment]
As these come up, let's just keep adding.

- [ ] NumberOfUnits
- [ ] UnitDensity
- [ ] SpatialUnitOccupiedPercentage

**Comment by macintoshpie** [comment]
@nllong is there a reason we closed this? I think it's probably low priority, but would be nice to fix now with major version change if someone ends up with some spare time

**Comment by nllong** [comment]
hmm, it looks like I'm the one who is flapping the status of this ticket. If there are more items to update the types on then we can either reopen this or create a new ticket with the specific items to address (i prefer the latter).

**Comment by macintoshpie** [comment]
I think part of this ticket would be finding types to fix. I'll update the description accordingly
