### ISSUE TITLE
Add AverageAnnualOperatingHours to Other Types

### ISSUE THREAD

**Issue by corymosiman12** [BuildingSync/schema#312]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

It is typical for run time / run hours / operating hours to be an important metric for certain system types. This was added to the `OnsiteStorageTransmissionGenerationSystemType` here: https://github.com/BuildingSync/schema/pull/311.

Opening this up to track adding `AverageAnnualOperatingHours` to:
- `FanSystemType`
- `PumpSystemType`
- `MotorSystemType`

Others?

**Describe alternatives you've considered**

**Additional context**

**Comment by JieXiong9119** [comment]
We may want to add `AverageAnnualOperatingHours` to other systems (e.g. boiler), as seen in Audette UDFs.

**Comment by macintoshpie** [comment]
Waiting for user-request/specific use-case
