### ISSUE TITLE
Addition of water conservation measures and associated fields to support EISA-432 project tracking and compliance #88

### ISSUE THREAD

**Issue by macintoshpie** [BuildingSync/schema#316]
Summarized WCMs are in [here](https://docs.google.com/spreadsheets/d/1tMIhnu336256J2alVWfqZ45RjbqERRwq/edit?usp=sharing&ouid=117281173110888138505&rtpof=true&sd=true).

**Comment by macintoshpie** [comment]
Most recent list(s) of ECMs along with my comments

List A (from [here](https://www.energy.gov/eere/femp/water-efficient-technology-opportunities))
- Distribution System Leak Detection
    - I think we would need to create `ChilledWaterHotWaterAndSteamDistributionSystems/MeasureName[text()="Repair leaks"]`
- Advanced Cooling Tower Controls
    - Does this mean install advanced controls or reconfigure the controls?
- Connectionless Food Steamers
    - I don't think we have a proper category for this currently, should it be `CookingSystems/MeasureName[text()="Install connectionless food steamers"]`?
- Multi-Stream Rotational Sprinkler Heads
    - I don't think we have a proper category for this currently and I'm not sure what it would be. We do have `WaterAndSewerConservationSystems/MeasureName[text()="Implement water efficient irrigation"]`.
- On-Site Wastewater Treatment Systems
    - does this fit under our existing `RenewableEnergySystems/MeasureName-text()="Install landfill gas, wastewater treatment plant digester gas, or coal bed methane power plant"`? Or would it go under `WaterAndSewerConservationSystems`?
- Rainwater Harvesting Systems
    - Would probably need to create `WaterAndSewerConservationSystems/MeasureName[text()="Add rainwater harvesting system"]`
- Sprinkler Automatic Shut-Off Devices
    - Not sure what this would be, but seems relevant to our existing `WaterAndSewerConservationSystems/MeasureName[text()="Implement water efficient irrigation"]`
- Steam Sterilizer Condensate Retrofit Kit
    - Not sure where this should go, according to the webpage by FEMP, it's commonly found in "hospitals, clinics, and laboratories"

List B (from [here](https://www.energy.gov/eere/femp/best-management-practices-water-efficiency))
- Distribution System Audits, Leak Detection, and Repair
    - I think this is covered by first bullet in list A
- Water-Efficient Landscaping
    - Not sure where this should live...
- Water-Efficient Irrigation
    - Covered by existing `WaterAndSewerConservationSystems/MeasureName[text()="Implement water efficient irrigation"]` (see list A)
- Toilets and Urinals
    - would this fall under`WaterAndSewerConservationSystems/MeasureName[text()="Install low-flow plumbing equipment"]`?
- Faucets and Showerheads
    - would this fall under `WaterAndSewerConservationSystems/MeasureName[text()="Install low-flow faucets and showerheads"]`?
- Steam Boiler Systems
    - would probably go under `BoilerPlantImprovements`, but I don't know what the measure name would be.
- Single-Pass Cooling Equipment
    - I'm not sure where this would go
- Cooling Tower Management
    - would this just be `ChillerPlantImprovements/MeasureName[text()="Add or replace cooling tower"]`?
- Commercial Kitchen Equipment
    - No place for this currently (see comment on Connectionless Food Steamers in list A)
- Laboratory and Medical Equipment
    - No place for this currently (see comment on Steam Sterilizer Condensate Retrofit Kit in list A)
- Other Water-Intensive Processes
    - Not sure where this would go?
- Alternative Water Sources
    - Not sure where this would go?

**Comment by nllong** [comment]
I've converted this to a google sheet [here](https://docs.google.com/spreadsheets/d/1eMa-oLXh5fGfJJ5g_r9af5_ypVAPiCMbpe9ELnhE9Ek/edit#gid=0). The first set of measures look good. However, the FEMP measures at the Steam Boiler down really have many more measures to consider. Do we need to add those measures as well (for example see: https://www.energy.gov/eere/femp/best-management-practice-8-steam-boiler-systems).

**Comment by nllong** [comment]
We are going to put this on the back burner for a bit. The actual task will require pulling out all the measures in each of the categories on [this page](https://www.energy.gov/eere/femp/best-management-practices-water-efficiency) and then deduping, naming, etc.

**Comment by nllong** [comment]
Okay, time to reopen this to generate the list of WCMs. The goal for now is to just create the list and send to PNNL for review. We can implement after approval.

The history of this ticket is interesting and I think is fully captured in the following: The sources of water conservation spreadsheet is [here](https://docs.google.com/spreadsheets/d/1lNI6jSUDQCwR1LnatIRdUFQ1c4sfWkEn/edit#gid=1860537313) and the current list of all ECMs and WCMs is [here](https://docs.google.com/spreadsheets/d/1UiUA7ukCa6uErhf7MbayxFO_Bfau49gf/edit#gid=1871393978). I think the design approach is to go through the sources spreadsheet and click on the links to the EERE websites. These websites have WCMs embedded in text, so I suggest copying the text to the "all ECMs and WCMs" spreadsheet and then create an initial technology category and measure name. We have a few ECMs that are existing in BuildingSync which we should deduplicate, but I think that can happen after we get all the data into the spreadsheet.

@JieXiong9119 can you start this task of getting everything in one place?

**Comment by JieXiong9119** [comment]
The summarized WCMs are in [here](https://docs.google.com/spreadsheets/d/1tMIhnu336256J2alVWfqZ45RjbqERRwq/edit?usp=sharing&ouid=117281173110888138505&rtpof=true&sd=true).

**Comment by macintoshpie** [comment]
@laurenliz22 to review doc above
