### ISSUE TITLE
Deduplicate elements: OtherControlTechnology through YearOfConstruction

### ISSUE THREAD

**Issue by macintoshpie** [BuildingSync/schema#325]
The schema redefines elements that should technically be references to a single element/type.

For each of the elements below:
1. Determine if the duplicate names are of the same "type", ie representing the same thing: actual type, description, etc.
2. If they are the same type, create a new element at the bottom of the schema and reference it in those places. Remove that element name from the `ignored_dupes` list in validation_spec.rb.
3. If they are not representing the same thing, create a new issue on GH describing the elements and their differences.

Below are the duplicated element names and their current line numbers at 37086c4579bcd66501ce7e82344fa3ca804dbe4e
```
OtherControlTechnology: [17032, 17226]
OtherControlTechnologyName: [17039, 17230]
OutputCapacity: [6455, 7422, 7655, 7750]
PipeInsulationThickness: [6785, 6825, 9753, 16649]
PipeLocation: [6797, 6837, 9765, 16661]
PortfolioManager: [655, 2233]
PrimaryFuel: [7800, 8077, 8474, 14054]
Priority: [2521, 16226]
RatePeriod: [3169, 3283, 3437]
RatePeriodName: [3172, 3286, 3440]
RatePeriods: [3166, 3280, 3434]
RatedCoolingSensibleHeatRatio: [6712, 7978, 8045]
RefrigerantChargeFactor: [6608, 7914]
RequiredVentilationRate: [8606, 8712]
Section: [1025, 14278, 14473]
SimplePayback: [2425, 2814, 2963, 5713]
Site: [73, 14216, 14411]
SiteEnergyUse: [4121, 15856]
SlabArea: [12577, 12881]
SlabExposedPerimeter: [12601, 12905]
SlabInsulationCondition: [12649, 12929]
SlabInsulationThickness: [12613, 12917]
SlabPerimeter: [12589, 12893]
SourceEnergyUse: [4145, 15863]
SourceEnergyUseIntensity: [4157, 15867]
Space: [1772, 14340, 14535]
SpaceID: [1381, 1449, 1517]
SpaceIDs: [1378, 1446, 1514]
StartTimestamp: [4438, 17902]
SteamBoilerMaximumOperatingPressure: [7608, 7730]
SteamBoilerMinimumOperatingPressure: [7596, 7718]
Story: [1089, 15640]
StreetAdditionalInfo: [14605, 14660]
SummerPeakElectricityReduction: [2365, 2592, 2903, 5568]
ThermalEfficiency: [6325, 7491]
ThermalZone: [1641, 14309, 14504]
ThermalZoneID: [1217, 1367, 1435, 1503]
ThermalZoneIDs: [1211, 1364, 1432, 1500]
TimeSeries: [3070, 18176, 18277, 18287, 18297, 18307]
Timer: [16992, 17206]
TransformerNeeded: [8991, 9047]
Unknown: [3634, 6409, 6649, 7795, 8072, 8469, 8802, 9067, 9392, 9569, 9577, 9688, 9699, 10590, 12801, 12935]
UtilityAccountNumber: [3816, 13958]
UtilityBillpayer: [3821, 13963]
UtilityMeterNumber: [3808, 13953]
VentilationControlMethods: [8640, 8724, 8785]
VentilationRate: [8594, 8700]
WaterSideEconomizer: [8246, 8379]
WaterSideEconomizerDBTemperatureMaximum: [8265, 8410]
WaterSideEconomizerTemperatureMaximum: [8253, 8398]
WaterUse: [244, 4314]
WeightedAverageLoad: [13127, 13215]
WinterPeakElectricityReduction: [2377, 2604, 2915, 5580]
YearOfConstruction: [941, 1055]
```

**Comment by Ryoken** [comment]
All of these instances were found to be identical. A base level element was created by the same name and all instances were converted into references:

OtherControlTechnologyName
OutputCapacity
PipeInsulationThickness
PipeLocationRatePeriodName
RatedCoolingSensibleHeatRatio
RefrigerantChargeFactor
RequiredVentilationRate
SimplePayback
SlabArea
SlabExposedPerimeter
SlabInsulationCondition
SlabInsulationThickness
SlabPerimeter\SourceEnergyUseIntensity
SpaceIDs
SteamBoilerMaximumOperatingPressure
SteamBoilerMinimumOperatingPressure
Story
StreetAdditionalInfo
SummerPeakElectricityReduction
ThermalEfficiency
ThermalZoneIDs
TimeSeries
TransformerNeeded
Unknown
UtilityAccountNumber
UtilityBillpayer
UtilityMeterNumber
VentilationControlMethods
VentilationRate
WaterSideEconomizerDBTemperatureMaximum
WaterSideEconomizerTemperatureMaximum
WeightedAverageLoad
WinterPeakElectricityReduction
YearOfConstruction

**Comment by Ryoken** [comment]
These instances were no longer duplicated as a result of consolidating one of the previously listed elements:

SpaceID
ThermalZoneID

**Comment by Ryoken** [comment]
These instances were identical save for minor differences in documentation. In each instance a more generic documentation was provided after consolidating into a base level element:

PortfolioManager
PrimaryFuel
StartTimestamp

**Comment by Ryoken** [comment]
These instances had a more complex change:

Priority
 - both instances describe a different type of priority
 - suggestion: rename first instance to "ImpactAnalysisPriority"

RatePeriod
 - all instances unique
 - suggestion: rename to "FlatRatePeriod", "TimeOfUseRatePeriod" and "TieredRatePeriod"

RatePeriods
 - all instances unique
 - suggestion: rename to "FlatRatePeriods", "TimeOfUseRatePeriods" and "TieredRatePeriods"

**Comment by Ryoken** [comment]
The remaining instances require some changes:

OtherControlTechnology
 - both instances nearly identical except for each use a slightly different type of "ControlStrategy"
 - suggestion: rename to "OtherGeneralControlTechnology" and "OtherLightingControlTechnology" or consolidate "ControlStrategy"

Section
 - third instance defines a section, first and second instances list section IDs
 - suggestion: create base element "LinkedSection" and reference with first and second instance

Site
 - third instance refers "SiteType", first and second instances list site IDs
 - suggestion: create base element "LinkedSite" and reference with first and second instance

SiteEnergyUse
 - all instances unique
 - suggestion: rename first to "SiteAnnualEnergyUse" or second to "SiteEnergyUseTypes"

SourceEnergyUse
 - all instances unique
 - suggestion: rename both

Space
 - first instance defines a space, second instance lists space IDs
 - suggestion: create base element "LinkedSpace" and reference with second instance

ThermalZone
 - third instance refers "ThermalZoneType", first and second instances list thermal zone IDs
 - suggestion: create base element "LinkedThermalZone" and reference with first and second instance

Timer
 - both instances nearly identical except for each use a slightly different type of "ControlStrategy"
 - suggestion: rename to "GeneralTimer" and "LightingTimer" or consolidate "ControlStrategy"

WaterSideEconomizer
 - both instances nearly identical except one has "WaterSideEconomizerTemperatureSetpoint"
 - suggestion: add "WaterSideEconomizerTemperatureSetpoint" to the other instance, then merge and reference both instances

WaterUseType
 - all instances unique
 - suggestion: rename second instance "AnnualWaterUse"

**Comment by Ryoken** [comment]
Moved remaining duplicates to https://github.com/BuildingSync/schema/issues/356
