### ISSUE TITLE
Remove redundant "Add or replace cooling tower" from Other HVAC

### ISSUE THREAD

**Issue by nllong** [BuildingSync/schema#330]
There are two measures with "Add or replace cooling tower", one in Chiller Plant Improvements and one in Other HVAC. 

Cooling towers should just exist in Chiller Plant Improvements.

**Comment by JieXiong9119** [comment]
Should I open a new PR or include it into the PR with other three changes?

**Comment by nllong** [comment]
yep, with a proposal too (which will be really short).
