### ISSUE TITLE
Move AT <> SEED Demo slides to BTO slide deck

### ISSUE THREAD

**Issue by macintoshpie** [BuildingSync/schema#380]
Current slides here: https://docs.google.com/presentation/d/1b_NgISxz88QV3tgcbDJoAMslVgTKTnwzHJmYElTEGTs/edit#slide=id.ge93ccb86ff_0_7

**Comment by macintoshpie** [comment]
@nllong can you share the BTO slide deck?

**Comment by nllong** [comment]
@macintoshpie  -- can you copy this presentation and use it as a template? https://drive.google.com/open?id=1WNWf-mKxrKW8kp4ha8sFTO7oYSDOLZyX
