### ISSUE TITLE
Compare terms to most updated BEDES dictionary

### ISSUE THREAD

**Issue by macintoshpie** [BuildingSync/schema#390]
## context
BSync uses BEDES terms to guide element names etc

## task
- download the most recent BEDES dictionary (2.5?), compare to older dictionaries to see if anything has been renamed/removed and add these changes to the 3.0 schema

**Comment by macintoshpie** [comment]
Removed terms:
- EnergyCostReductionThroughRateAdjustments
- EnergyRelatedProcessImprovements

@nllong is there anything we should do about this or should we keep these Measure Technology Categories in v3?

**Comment by macintoshpie** [comment]
We just reached out to the BEDES team to learn why these terms were removed. Once we hear back we will make the call for what BSync should do.

**Comment by markborkum** [comment]
@macintoshpie This would affect Audit Template. There are 40 buildings with energy savings measures that use one or both of the removed terms:

* EnergyCostReductionThroughRateAdjustments - 13 buildings
* EnergyRelatedProcessImprovements - 28 buildings

**Comment by macintoshpie** [comment]
Thanks @markborkum 

It seems like we should not deprecate these elements then, @nllong  do you agree?

**Comment by nllong** [comment]
yeah, let's *not* deprecate. I'm sure CTS has these implemented as well.

**Comment by macintoshpie** [comment]
Closing this issue. To summarize we found two terms BEDES removed which BSync uses, but due to current usage of those element we aren't deprecating them.
