### ISSUE TITLE
Remove xmlns and nX:source in example files

### ISSUE THREAD

**Issue by nllong** [BuildingSync/schema#427]
The ASHRAE 211 export example file still has the `xmlns` and `nX:source` in the interval reading element. These should be removed to ease readability.  

V3: https://github.com/BuildingSync/schema/blob/develop-v3/examples/ASHRAE%20211%20Export.xml#L1382-L1390
V2: https://github.com/BuildingSync/schema/blob/develop-v2/examples/ASHRAE%20211%20Export.xml#L1382-L1390

**Comment by JieXiong9119** [comment]
The oldest PR/commit we could trace back where these redundant attributes exist is #48. It's still not clear yet how these were generated, but one guess is that they were generated at the beginning with the use of [std211 translator](https://github.com/BuildingSync/std211-translator). Given the fact that this translator is out of date for many versions of BuildingSync, I suggest we do not investigate into it until necessary.

**Comment by nllong** [comment]
> The oldest PR/commit we could trace back where these redundant attributes exist is #48. It's still not clear yet how these were generated, but one guess is that they were generated at the beginning with the use of [std211 translator](https://github.com/BuildingSync/std211-translator). Given the fact that this translator is out of date for many versions of BuildingSync, I suggest we do not investigate into it until necessary.

agreed.
