### ISSUE TITLE
[6/30/23] Adding to BuildingSync's Schema Milestone

### ISSUE THREAD

**Issue by laurenliz22** [BuildingSync/schema#466]

**Comment by JieXiong9119** [comment]
Review UDFs list:
https://docs.google.com/spreadsheets/d/1-XxIsChQ2E-vdFZ4h7BIhCoLEcpHoQ0Y/edit?pli=1#gid=984854597
https://docs.google.com/spreadsheets/d/1LaztYTrT7_iPQTcTDEQZAB2fVJ23G3Wo/edit#gid=595543811

**Comment by JieXiong9119** [comment]
UDFs:
#473 
#475 
#476 
CERL:
#477 
#478
