### ISSUE TITLE
Formal process for using the issue feature for requesting extensions to BuildingSync

### ISSUE THREAD

**Issue by chrisbalbach** [BuildingSync/schema#47]
Under the docs section of this repository, can a document describing a (semi-formal?) process for requesting additional data fields be added?

For example - what are the **minimum** set of supportive data that should be submitted by a user along with a new field request, and in what specific type of format? I am thinking along the lines of streamlining a review process by minimizing the 'back and forth' needed to communicate clarity and intent. 

Also, if/when new data fields are adopted/incorporated into BuildingSync, does this also mean they will become included into the 'official' set of BEDES objects?

**Comment by nllong** [comment]
I agree that this is needed. I envision a document and also issue templates for making sure the right amount of data are collected to make adding/extending to BuildingSync easy. 

The integration into BEDES needs to be discussed further.

I'll leave this ticket open until we have documented the semi-formal process.

**Comment by nllong** [comment]
@chrisbalbach -- please see https://github.com/BuildingSync/schema/tree/develop/proposals and let us know your thoughts. We will be discussing this at the ASHRAE meeting.
