### ISSUE TITLE
Connect Utilities and Sites

### ISSUE THREAD

**Issue by ashleyHutton** [BuildingSync/schema#74]
To start: This BuildingSync schema is incredible, and you guys have done a wonderful job developing it!

I'm using this schema on an energy profiling tool that takes utility data at a site/building level and evaluates the potential impacts of various measures. After spending time looking through the schema, I can't come up with a clear way to connect utilities and their rate schedules with the sites/buildings they belong to.

The closest I could come to accessing a building's utilities was through linked facilities. If you match the primary fuels of the building's systems with the resource use's end uses, you can use those utility ids to capture which utilities are related to the building in question. However, this does not seem correct because resource uses are in the context of a report and they have their own end use, which does not appear to correspond to a single system.

Any insight into how sites and utilities relate would be much appreciated. Thanks!

**Comment by jasondegraw** [comment]
@ashleyHutton Our example files are a little deficient in this area, but I think at least part of what you want to do is documented in the "ASHRAE 211 Export.xml" example file. It may be the part that you've already found. The first scenario in that file has a ResourceUse item "Resource2" that is linked to a utility through a utility ID:

https://github.com/BuildingSync/schema/blob/e46dca08e5f2c289ac728cd20c6e2e3a4768ad4b/examples/ASHRAE%20211%20Export.xml#L1260-L1262

Down at the bottom of the element it refers to the building with a LinkedPremises element:

https://github.com/BuildingSync/schema/blob/e46dca08e5f2c289ac728cd20c6e2e3a4768ad4b/examples/ASHRAE%20211%20Export.xml#L2479-L2483

I think that gets some of what you're asking about, but I'm not seeing a good way to unambiguously connect a particular system to a utility. 

Using the fuel type feels like an unsatisfactory workaround, so I'll keep looking for a better solution. If this turns out to be a deficiency in the schema, would you be willing to review potential changes to the schema? It wouldn't be a huge lift for you, we'll come up with a solution and run it by you to make sure it addresses your needs.

**Comment by nathancolgate** [comment]
Hi @jasondegraw . I work with @ashleyHutton on our energy project. Below is a rough representation of how we are solving this internally in our tool. We are trying to define the information that would be describe a specific connection to the utility... almost like a meter.

There might be a place to incorporate Utility Bills at this level as well. We fantasize about Utility Companies providing historical utility bill data in a standard format. :)

Anyway, the following is totally unsolicited, but perhaps it will help the conversation:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<BuildingSync xmlns="http://buildingsync.net/schemas/bedes-auc/2019" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://buildingsync.net/schemas/bedes-auc/2019 ../BuildingSync.xsd">
  <Facilities>
    <Facility>
      <UtilityMeters>
        <UtilityMeter>
          <UtilityMeterNumber>123456</UtilityMeterNumber>
          <UtilityCompanyName>Nick's Utility</UtilityCompanyName>
          <ResourceType>Electricity</ResourceType>
          <RateSchedule IDref="RateSchedule1" />
          <LinkedPremises>
            <Site>
              <LinkedSiteID IDref="Site1"/>
            </Site>
          </LinkedPremises>
          <UtilityBills>
            <UtilityBill>
              <StartDate>2018-01-05</StartDate>
              <EndDate>2018-02-04</EndDate>
              <CostInUSD>8540.30</CostInUSD>
              <Source>Utility</Source>
              <UserDefinedFields>
                <UserDefinedField>
                  <FieldName>Attachment</FieldName>
                  <FieldValue>https://aws.s3/jan2018bill.pdf</FieldValue>
                </UserDefinedField>
              </UserDefinedFields>
            </UtilityBill>
            <UtilityBill>
              <StartDate>2018-01-05</StartDate>
              <EndDate>2018-02-04</EndDate>
              <CostInUSD>8320.60</CostInUSD>
              <Source>Simulation</Source>
              <UserDefinedFields>
                <UserDefinedField>
                  <FieldName>ScenarioID</FieldName>
                  <FieldValue>Scenario12</FieldValue>
                </UserDefinedField>
              </UserDefinedFields>
            </UtilityBill>
          </UtilityBills>
        </UtilityMeter>
      </UtilityMeters>
    </Facility>
  </Facilities>
</BuildingSync>
```

Thanks in advance for your consideration.

**Comment by jasondegraw** [comment]
@nathancolgate Thanks, that's great! We've been spending a lot of time recently on reducing the use of `UserDefinedField` elements, so I think I can shuffle that around to represent most of it in the current schema. How about this:

```
<?xml version="1.0" encoding="UTF-8"?>
<BuildingSync xmlns="http://buildingsync.net/schemas/bedes-auc/2019" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://buildingsync.net/schemas/bedes-auc/2019 ../BuildingSync.xsd">
  <Facilities>
    <Facility>
      <Sites>
        <Site ID="Site1"/>
      </Sites>
      <Report>
        <Scenarios>
          <Scenario ID="Measured1">
            <ResourceUses>
              <ResourceUse ID="ResourceUse1">
                <EnergyResource>Electricity</EnergyResource>
                <UtilityIDs>
                  <UtilityID IDref="UtilityA"/>
                </UtilityIDs>
              </ResourceUse>
            </ResourceUses>
            <TimeSeriesData>
              <TimeSeries>
                <ReadingType>Total</ReadingType>
                <TimeSeriesReadingQuantity>Currency</TimeSeriesReadingQuantity>
                <StartTimeStamp>2018-01-05T00:00:00</StartTimeStamp>
                <EndTimeStamp>2018-02-04T00:00:00</EndTimeStamp>
                <IntervalReading a:Source="Utility" xmlns:a="http://buildingsync.net/schemas/bedes-auc/2019">8540.30</IntervalReading>
                <ResourceUseID IDref="ResourceUse1"/>
                <UserDefinedFields>
                  <UserDefinedField>
                    <FieldName>Attachment</FieldName>
                    <FieldValue>https://aws.s3/jan2018bill.pdf</FieldValue>
                  </UserDefinedField>
                </UserDefinedFields>
              </TimeSeries>
            </TimeSeriesData>
            <LinkedPremises>
              <Site>
                <LinkedSiteID IDref="Site1"/>
              </Site>
            </LinkedPremises>
          </Scenario>
          <Scenario ID="Simulated2">
            <ScenarioName>Scenario12</ScenarioName>
            <ResourceUses>
              <ResourceUse ID="ResourceUse2">
                <EnergyResource>Electricity</EnergyResource>
              </ResourceUse>
            </ResourceUses>
            <TimeSeriesData>
              <TimeSeries>
                <ReadingType>Total</ReadingType>
                <TimeSeriesReadingQuantity>Currency</TimeSeriesReadingQuantity>
                <StartTimeStamp>2018-01-05T00:00:00</StartTimeStamp>
                <EndTimeStamp>2018-02-04T00:00:00</EndTimeStamp>
                <IntervalReading a:Source="Simulation" xmlns:a="http://buildingsync.net/schemas/bedes-auc/2019">8320.60</IntervalReading>
                <ResourceUseID IDref="ResourceUse2"/>
              </TimeSeries>
            </TimeSeriesData>
          </Scenario>
        </Scenarios>
        <Utilities>
          <Utility ID="UtilityA">
            <RateSchedules>
              <RateSchedule ID="RateSchedule1"/>
            </RateSchedules>
            <UtilityName>Nick's Utility</UtilityName>
            <UtilityMeterNumbers>
              <UtilityMeterNumber>123456</UtilityMeterNumber>
            </UtilityMeterNumbers>
          </Utility>
        </Utilities>
      </Report>
    </Facility>
  </Facilities>
</BuildingSync>
```
The `TimeSeriesData` element is a little hard to use and representation of time series is something that's under consideration for improvement, but for now this passes validation for me. Did I get all of you items transferred over?

The only remaining `UserDefinedField` is the linkage to the external file, and there's been some work done to better support that as well (see #60, mainly focused on gbXML etc.). It's still in progress.

**Comment by nathancolgate** [comment]
@jasondegraw That is totally sufficient for us. Thanks!

I can, however, imagine a scenario in which someone is designing a tool that provides insight into which Rate Schedule someone should use. In that case, everything else is a given and the only thing that changes between scenarios is which Meters are using which Rate Schedules. I don't know if that is a real problem utility clients have, though.

That concern could go for any permutation of information too (i.e. given the same energy demand / climate info / rate schedules: should I construct building A with systems 1,2,3 or building B with systems 4,5,6?).

Blegh.

I reiterate @ashleyHutton 's thanks for your work on this. Developing a standard is hard!

**Comment by nllong** [comment]
Is this still an issue? Seems like we have a workaround.

**Comment by ashleyHutton** [comment]
@nllong I think this can be closed, thanks!
